// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPrQsU0ztTgBkwBHeC9whJCV1DAFfti0',
    appId: '1:557404820558:web:d559e7b7ee635f39a7df1f',
    messagingSenderId: '557404820558',
    projectId: 'polywise-push',
    authDomain: 'polywise-push.firebaseapp.com',
    storageBucket: 'polywise-push.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM7d_oAm7uIwJDsAuJMxmcVkOXtA2H-s',
    appId: '1:557404820558:android:9dd96da1e2bec5d2a7df1f',
    messagingSenderId: '557404820558',
    projectId: 'polywise-push',
    storageBucket: 'polywise-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQF9cEs5VolO9l3QfK__3T2dg_XlLk_gk',
    appId: '1:557404820558:ios:b708f1dd74ed90cea7df1f',
    messagingSenderId: '557404820558',
    projectId: 'polywise-push',
    storageBucket: 'polywise-push.firebasestorage.app',
    iosBundleId: 'com.terrydodson.polywiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQF9cEs5VolO9l3QfK__3T2dg_XlLk_gk',
    appId: '1:557404820558:ios:2cec2675fb4b2c42a7df1f',
    messagingSenderId: '557404820558',
    projectId: 'polywise-push',
    storageBucket: 'polywise-push.firebasestorage.app',
    iosBundleId: 'com.example.barcodeScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMPrQsU0ztTgBkwBHeC9whJCV1DAFfti0',
    appId: '1:557404820558:web:e6fad76ec56df9b3a7df1f',
    messagingSenderId: '557404820558',
    projectId: 'polywise-push',
    authDomain: 'polywise-push.firebaseapp.com',
    storageBucket: 'polywise-push.firebasestorage.app',
  );
}
